# Generated by Django 5.0.7 on 2024-08-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_char_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_char',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
